#!/bin/bash

mkdir_vagrant() {
	local DIR=$1/vagrant_debian
	echo $DIR
	mkdir -p $DIR
	export VAGRANT_HOME=$DIR
	cd $DIR
}

init_vagrant() {
	vagrant up
	vagrant plugin install vagrant-vbguest
	vagrant vb-guest
	vagrant reload
}

fill_vagrant_file() {
# This function is intentionally not well formatted because 
# there cannot be any space before the end string of a heredoc.
cat > Vagrantfile << EOM
	Vagrant.configure("2") do |config|
	config.vm.box = "debian/stretch64"
	config.vm.synced_folder ".", "/git"
end
EOM
# end string
}

if [ $# -eq 0 ]
	then
		echo "Usage : ./init_vagrant <PATH_TO_PARENT_DIR>"
	else
		mkdir_vagrant $1
		fill_vagrant_file
		init_vagrant
		vagrant ssh
fi
